### ISSUE TITLE
Ha-Htoe is mistakenly converted to Wa-Swe

### ISSUE THREAD

**Issue by yelinaung** [yelinaung/mmfont#1]
In `zg12uni51`, "Ha-Htoe is mistakenly converted to Wa-Swe"

Test case 

`assert_equal 'ဘောလုံးကန်တာမှ ကောင်းဦးမယ်', Mmfont::Converter.new.zg12uni51('ေဘာလုံးကန္တာမွ ေကာင္းဦးမယ္')`

```
Expected: "ဘောလုံးကန်တာမှ ကောင်းဦးမယ်"
  Actual: "ဘောလုံးကန်တာမွ ကောင်းဦးမယ်"
```

**Comment by yelinaung** [comment]
@dreamingblackcat Is that fixed in your gem ?

**Comment by sanlinnaing** [comment]
I fixed on my fork java code, bro. All medial Ha are translated to medial wa. I found this issues on such as medial ha, medial wa + ha, zero to Wa Lone fix, digit 7 and YaGauk fix.
And another issues is in ဋ္ဌ > ဋ + virama + ဌ is incorrect order. Check it bro.
And no other spelling check on zawgyi user typed error like double medial wa, double I -  vowel, double U dependent vowel.
Ko ThuRa reply on my issues, take a look bro. There is a rule file we can correct.

**Comment by yelinaung** [comment]
@sanlinnaing Calm down. Nobody's arguing anything with you. I have seen the issue on Paytan and just cross referencing. well, the idea is not to fix the generated code but to be fix the rule files. I have checked. If you have fixed the other issues for Paytan, can you just comment under respective issue and send a pull request with changes to the rule files ? Thank you.

**Comment by sanlinnaing** [comment]
I'm not arguing with anyone bro. Why are you so serious? 😃😃. Just information bro. Actually, I am not familiar with python.

**Comment by yelinaung** [comment]
I am always serious. This issue is closed. Can we discuss about other
issues on paytan repo ? Thanks.
၂၀၁၅ ဖေဖော်ဝါရီ ၁၇ ၁၄:၁၁တွင် "San Lin Naing" notifications@github.com
ရေးခဲ့:
